# Generated by Django 2.2.13 on 2021-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_books_take',
            field=models.IntegerField(default=0),
        ),
    ]
